### ISSUE TITLE
请问注册后登录后怎么进入管理页面

### ISSUE THREAD

**Issue by zqcccc** [XboxYan/koa-blog#3]
注册后登录后
![image](https://user-images.githubusercontent.com/19168323/54729496-d91df780-4bbe-11e9-8c9d-c0e4d4991448.png)
然后手动输入地址进入 http://localhost:3000/#/admin 却跳出来的是登录界面

**Comment by XboxYan** [comment]
你可以看看`app.js`，那里有一个过滤器，检查一下你的逻辑。

如果满足条件才会跳到你所需的页面，否则就会强制跳转到登录。

![image](https://user-images.githubusercontent.com/19424274/54730056-a6c1c980-4bc1-11e9-99af-f0c952cc6b2f.png)

**Comment by zqcccc** [comment]
原来是 isAdmin 是 false 导致的，注册时注意一下就好了，谢谢
